{{- $fullName := include "wach.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "wach.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.tls.enabled }}
    networking.gke.io/managed-certificates: {{ $fullName }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
        {{- range .Values.ingress.paths }}
        - path: {{ .path }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
        {{- end }}
