apiVersion: v1
kind: Service
metadata:
  name: {{ include "wach.fullname" . }}
  labels:
    {{- include "wach.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wach.selectorLabels" . | nindent 4 }}
