# Default values for wach.
replicaCount: 1

image:
  repository: t3mu/wach
  pullPolicy: IfNotPresent
  tag: "dev"

serviceAccount:
  # Specifies whether a service account should be created
  create: true

service:
  port: 80

ingress:
  paths:
  - path: /
  annotations: {}

imagePullSecrets: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Enable managed certificates. Does not work locally
# At least one domain is required with tls. Configure the domains to point at ingress ip address
tls:
  enabled: false
  domains: []